name: Spring Boot Selenium UI Test

on:
  push:
    branches:
      - feature/*

jobs:
  generate-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Python 설치 및 라이브러리 설치
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3. Python 스크립트 실행
      - name: Generate Selenium tests using OpenAI
        env:
          AI_ML_API_KEY: ${{ secrets.AI_ML_API_KEY }}
        run: |
          python scripts/generate_ui_tests.py

      # 4. Maven 테스트 실행
      - name: Run Selenium UI tests
        run: |
          mvn test

      # 5. PR 승인 여부 설정
      - name: Approve or Reject PR
        run: |
          if mvn test --batch-mode | grep -q "BUILD SUCCESS"; then
            echo "Tests passed. PR approved."
          else
            echo "Tests failed. PR rejected."
            exit 1
